name: Deploy Vite React App

on:
  push:
    branches:
      - main # ou la branche que vous souhaitez déployer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Choisissez la version de Node.js appropriée

      - name: Installer les dépendances
        run: npm install # ou yarn install si vous utilisez Yarn

      - name: Construire l'application
        run: npm run build # Remplacez par votre commande de construction

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Remplacez par le répertoire de build de votre application
